version: '3.8'

services:
  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_DATABASE: trainee_management
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:latest
    container_name: redis_server 
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    
  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_lib:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  
  trainee_management:
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    image: trainee_management:latest
    container_name: trainee_management_app
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - ../Files:/app/data
    
  trainee_worker:
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    image: rabbitmq_worker:latest
    container_name: rabbitmq_worker
    restart: always
    env_file:
      - .env
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    

 
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  
 
volumes:
  mysql_data:
  redis_data:
  rabbitmq_lib:
    driver: local
  rabbitmq_log:
    driver: local
  
